# Generated by Django 2.0.2 on 2018-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180626_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field='120', upload_to='images/', width_field='90'),
        ),
    ]
